scala_library(name='slick',
  dependencies=[
    '3rdparty/com/typesafe:slick',
    '3rdparty/com/twitter:bijection-util',
  ],
  sources=globs('*.scala', 'dao/*.scala', 'logging/*.scala'),
  scope='default',
)
