scala_library(name='slick',
  dependencies=[
    '3rdparty/com/typesafe:slick',
    '3rdparty/com/twitter:bijection-util',
    '3rdparty/org/clapper:grizzled-slf4j',
  ],
  sources=globs('*.scala', 'dao/*.scala', 'logging/*.scala'),
  scope='default',
)
